nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: false
        allow_headers: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8080']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600
